name: Build and Release Minecraft Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Oracle JDK 23
      - name: Set up Oracle JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '23'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Upload the JAR file as an artifact (for debugging or download)
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-plugin-jar
          path: target/*.jar

      # Step 5: Upload the JAR to GitHub Releases
      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
